### ISSUE TITLE
No provider for t! after importing ng2-cache-service module

### ISSUE THREAD

**Issue by JohannesHoppe** [seanstanden/ng-blog#1]
I just came around, searching for a ready-to use implementation of `HttpCache ` (I'm lazy ;-)).

Please note this:
https://stackoverflow.com/questions/45277235/angular4-no-provider-for-t-after-importing-ng2-cache-service-module

```
ng build --prod --aot
```
will fail with `ng2-cache-service`. Switch to ` ng2-cache` to fix that problem!

Cheers!

**Comment by seanstanden** [comment]
Awesome, thanks Johannes. Updated!

**Comment by JohannesHoppe** [comment]
You're welcome!
